# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
roles:
  - name: cloudalchemy.prometheus
    src: https://github.com/cloudalchemy/ansible-prometheus.git
    version: 4.0.0
  - name: cloudalchemy.grafana
    version: 0.18.0
