#!/usr/bin/env python3
# This hook is called with the following parameters:
# argv[1] -- Name of the remote to which the push is being done
# argv[2] -- URL to which the push is being done
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#
import sys, re, os
from git import Repo

repo = Repo('.', search_parent_directories=True)
git_root = repo.git.rev_parse("--show-toplevel")
sys.path.insert(1, git_root+'/dev')

from license_check import license_check
from ansiblelinter import linter
from commit_messages import check_commit_messages

def get_commits():
    z40=0000000000000000000000000000000000000000
    ret = 0
    ranges = []
    for line in sys.stdin:
        local_ref, local_sha, remote_ref, remote_sha = line.strip().split(' ')
        if local_sha == z40:
            #handle delete
            pass
        else:
            if remote_sha == z40:
                ranges.append(local_sha)
            else:
                ranges.append(remote_sha+'..'+local_sha)
    return ranges

if __name__ == '__main__':
    ret = 0
    if "TDP_NO_COMMIT_CHECKS" not in os.environ:
        ret = check_commit_messages(get_commits())
    sys.argv = [ re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])]
    if "TDP_NO_LICENSE_CHECKS" not in os.environ:
        ret += license_check(None)
    if "TDP_NO_LINT" not in os.environ:
        ret += linter()
    if ret != 0:
        print("====================================================================")
        print("= pre_push check errors where found.                               =")
        print("= To disable checks you can export one or several of these :       =")
        print("=  - TDP_NO_COMMIT_CHECKS                                          =")
        print("=  - TDP_NO_LICENSE_CHECKS                                         =")
        print("=  - TDP_NO_LINT                                                   =")
        print("====================================================================")
    sys.exit(ret)
