# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Determine group name
  ansible.builtin.set_fact:
    group_name: "{{ component.value.group | default(service.key + '_' + component.key) }}"

- name: Parse prometheus scrape configs
  ansible.builtin.include_tasks: config_prometheus_scrapes.yml
  when: job.exporter_port is defined and job.exporter_port | int  > 0
  loop: "{{ component.value.jobs }}"
  loop_control:
    loop_var: job
    index_var: job_num
    label: "{{ service.key }}_{{ component.key }}_{{ job_num }}"
