# Copyright 2022 Adaltas
# SPDX-License-Identifier: MIT

---
- name: Restart Prometheus server
  ansible.builtin.service:
    name: prometheus
    state: restarted
    enabled: "{{ prometheus_server_start_on_boot }}"
