# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
- name: Start Prometheus server
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: "{{ prometheus_start_on_boot }}"
