# Copyright 2022 Adaltas
# SPDX-License-Identifier: MIT

---
- name: Stop Prometheus server
  ansible.builtin.service:
    name: prometheus
    state: stopped
    enabled: "{{ prometheus_server_start_on_boot }}"
