# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
- name: Stop Prometheus server
  ansible.builtin.service:
    name: prometheus
    state: stopped
    enabled: "{{ prometheus_server_start_on_boot }}"
