# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Ensure loki's group exists
  include_role:
    name: tosit.tdp.utils.group
  vars:
    group: "{{ loki_group }}"

- name: Ensure loki's user exists
  include_role:
    name: tosit.tdp.utils.user
  vars:
    user: "{{ loki_user }}"
    group: "{{ loki_group }}"

- name: Upload {{ loki_dist_file }}
  copy:
    src: files/{{ loki_dist_file }}
    dest: /tmp
    owner: root
    group: root
    mode: "644"
  diff: false

- name: Ensure {{ loki_root_dir }}/{{ loki_release }} exists
  file:
    path: "{{ loki_root_dir }}/{{ loki_release }}"
    state: directory
    owner: root
    group: root
    mode: "755"

- name: Extract {{ loki_dist_file }}
  unarchive:
    src: /tmp/{{ loki_dist_file }}
    dest: "{{ loki_root_dir }}/{{ loki_release }}"
    group: root
    owner: root
    mode: "755"
    remote_src: true
    creates: "{{ loki_root_dir }}/{{ loki_release }}/loki-linux-amd64"

- name: Create symbolic link to loki installation
  file:
    src: "{{ loki_root_dir }}/{{ loki_release }}"
    dest: "{{ loki_install_dir }}"
    state: link

- name: Ensure {{ loki_data_dir }} exists
  file:
    path: "{{ loki_data_dir }}"
    state: directory
    owner: "{{ loki_user }}"
    group: "{{ loki_group }}"
    mode: "750"

- name: Ensure {{ loki_conf_dir }} exists
  file:
    path: "{{ loki_conf_dir }}"
    state: directory
    owner: "{{ loki_user }}"
    group: "{{ loki_group }}"
    mode: "755"

- name: Template loki service file
  template:
    src: loki.service.j2
    dest: /usr/lib/systemd/system/loki.service
    group: root
    owner: root
    mode: "644"
  notify:
  - systemctl daemon-reload
