# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Assert loki is running 
  ansible.builtin.assert:
    that:
      - ansible_facts.services['loki.service'].state == "running"
    quiet: true
