# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Start node-exporter
  ansible.builtin.service:
    name: node-exporter
    state: started
    enabled: "{{ node_exporter_start_on_boot }}"
