# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
- name: Start Alertmanager server
  ansible.builtin.service:
    name: alertmanager
    state: started
    enabled: "{{ alertmanager_server_start_on_boot }}"
