# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0
---
- name: Stop Alertmanager server
  ansible.builtin.service:
    name: alertmanager
    state: stopped
    enabled: "{{ alertmanager_server_start_on_boot }}"
