{
 "title": "TDP HDFS",
 "tags": [
  "tdp",
  "hdfs",
  "prometheus",
  "jmx",
  "tdp-custom"
 ],
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "ActiveNameNode",
    "query": {
     "query": "query_result(Hadoop_NameNode_MillisSinceLastLoadedEdits{ job=\"hdfs_namenode\"} == 0) "
    }
   }
  ]
 },
 "panels": [
  { "title": "HDFS Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Name Node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_MillisSinceLastLoadedEdits{ job=\"hdfs_namenode\"} == 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NumAliveConnections",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_NumOpenConnections{job=~\"hdfs_namenode\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HDFS NameNode heap (JVM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_MemHeapUsedM{ job=\"hdfs_namenode\"}",
     "legendFormat": "{{ instance }} heap used"
    },
    {
     "expr": "avg(Hadoop_NameNode_MemHeapMaxM{ job=\"hdfs_namenode\"})",
     "legendFormat": "Max heap"
    },
    {
     "expr": "avg(Hadoop_NameNode_MemHeapMaxM{ job=\"hdfs_namenode\"})*1.1",
     "legendFormat": "MaxGraph"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{instance=~\"$ActiveNameNode\",job=~\"hdfs_namenode\"}",
     "legendFormat": "Uptime :"
    }
   ]
  },
  {
   "title": "NameNode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used File System Capacity (percent)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100*(Hadoop_NameNode_CapacityUsed{job=~\"hdfs_namenode\",name=\"FSNamesystem\"}/Hadoop_NameNode_CapacityTotal{job=~\"hdfs_namenode\",name=\"FSNamesystem\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "NameNode Capacity Used (total)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "Hadoop_NameNode_CapacityUsed{job=~\"hdfs_namenode\",name=\"FSNamesystem\"}/(1024*1024)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "NameNode Total Blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "Hadoop_NameNode_BlocksTotal{job=~\"hdfs_namenode\",name=\"FSNamesystemState\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Corrupted Blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "Hadoop_NameNode_CorruptBlocks{job=~\"hdfs_namenode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Under Replicated Blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "Hadoop_NameNode_UnderReplicatedBlocks{job=~\"hdfs_namenode\", name=\"FSNamesystem\",}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JournalNode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "JournalNode Alive Connections",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "Hadoop_JournalNode_NumOpenConnections{job=~\"hdfs_journal_node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JournalNode Operations per minutes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "rate(Hadoop_JournalNode_JournalNumOps{job=~\"hdfs_journal_node\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JournalNode Batches Writen per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "rate(Hadoop_JournalNode_BatchesWritten{job=~\"hdfs_journal_node\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "Hadoop_JournalNode_CallQueueLength{job=~\"hdfs_journal_node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JournalNode Operations Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "Hadoop_JournalNode_JournalAvgTime{job=~\"hdfs_journal_node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JournalNode Batches Lagging",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "Hadoop_JournalNode_BatchesWrittenWhileLagging{job=~\"hdfs_journal_node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DataNode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "DataNode FSDatasetState Used",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100*(Hadoop_DataNode_DfsUsed{ job=\"hdfs_datanode\",name=\"FSDatasetState\",}/Hadoop_DataNode_Capacity{ job=\"hdfs_datanode\",name=\"FSDatasetState\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DataNode Reads",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_ReadIoRateNumOps{ job=\"hdfs_datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DataNode Writes",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_WriteIoRateNumOps{ job=\"hdfs_datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DataNode Stored Data",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_DfsUsed{ job=\"hdfs_datanode\",name=\"FSDatasetState\",}/(1024*1024)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DataNode Reads Latency",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_ReadIoRateAvgTime{ job=\"hdfs_datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DataNode Writes Latency",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_WriteIoRateAvgTime{job=\"hdfs_datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}