{
 "title": "TDP zookeeper",
 "description": "Dashboard for TDP ZooKeeper (3.4.6) metrics generated by Prometheus JMX exporter",
 "tags": [
  "tdp",
  "zookeeper",
  "prometheus",
  "jmx",
  "tdp-custom"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "zookeeper_server" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "leader",
    "query": {
     "query": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_MaxSessionTimeout\",job=~\"$job\",name2=\"Leader\"}"
    }
   },
   { "name": "quorum", "query": "3" }
  ]
 },
 "panels": [
  {
   "title": "Leader",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_MaxSessionTimeout\",instance=~\"$instance\",job=~\"$job\",name2=\"Leader\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Zookeeper instances",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_NumAliveConnections\"}"
    },
    {
     "expr": "up{service=\"zookeeper\",component=\"server\"}",
     "legendFormat": "Up"
    },
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_NodeCount\"}",
     "legendFormat": "NodeCount"
    },
    {
     "expr": "{__name__=~\"java_lang_Runtime_Uptime\",service=\"zookeeper\",component=\"server\"}",
     "legendFormat": "UpTime"
    }
   ]
  },
  {
   "title": "Nodes Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max({__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_QuorumSize\"})",
     "legendFormat": "Quorum"
    },
    {
     "expr": "max({__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_QuorumSize\"}) -  count(up{service=\"zookeeper\", component=\"server\"} == 1)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ZNodeCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_NodeCount\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{ instance }} ZNodeCount"
    }
   ]
  },
  {
   "title": "ZNodeCountRate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate({__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_NodeCount\",instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{instance}} ZNodeCountRate"
    }
   ]
  },
  {
   "title": "PacketsReceived",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase({__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_PacketsReceived\",instance=~\"$instance\",job=~\"$job\", name3=\"\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PacketsSent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase({__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_PacketsSent\",instance=~\"$instance\",job=~\"$job\", name3=\"\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NumAliveConnections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_NumAliveConnections\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} NumAliveConnections"
    }
   ]
  },
  {
   "title": "MinMaxAvgRequestLatency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_MaxRequestLatency\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} MaxRequestLatency"
    },
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_MinRequestLatency\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} MinRequestLatency"
    },
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_AvgRequestLatency\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} AvgRequestLatency"
    }
   ]
  },
  {
   "title": "WatchCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_WatchCount\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} WatchCount"
    }
   ]
  },
  {
   "title": "OutstandingRequests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_OutstandingRequests\",instance=~\"$instance\",job=~\"$job\", name3=\"\"}",
     "legendFormat": "{{instance}} OutstandingRequests"
    }
   ]
  }
 ]
}