{
 "title": "TDP YARN",
 "description": "Dashboard for TDP YARN service generated by Prometheus exporters",
 "tags": [
  "tdp",
  "yarn",
  "prometheus",
  "jmx",
  "tdp-custom"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "service", "query": "yarn" },
   {
    "name": "queue",
    "label": "Queue",
    "query": {
     "query": "label_values({ service=\"$service\"}, q1)"
    }
   },
   {
    "name": "activeRM",
    "query": {
     "query": "query_result(Hadoop_ResourceManager_NumActiveNMs{ service=\"$service\"} > 0)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Components status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "YARN Active ResourceManager",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_NumActiveNMs{instance=\"$activeRM\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "YARN ResourceManagers heap (JVM)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_MemHeapUsedM{ job=\"yarn_ressource_manager\"}",
     "legendFormat": "{{ instance }} heap used"
    },
    {
     "expr": "avg(Hadoop_ResourceManager_MemHeapMaxM{ job=\"yarn_ressource_manager\"})",
     "legendFormat": "Max heap"
    },
    {
     "expr": "avg(Hadoop_ResourceManager_MemHeapMaxM{ job=\"yarn_ressource_manager\"})*1.1",
     "legendFormat": "MaxGraph"
    }
   ]
  },
  {
   "title": "YARN NodeManagers status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_NumActiveNMs{ job=\"yarn_ressource_manager\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "max(Hadoop_ResourceManager_NumUnhealthyNMs{ job=\"yarn_ressource_manager\"})",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "max(Hadoop_ResourceManager_NumShutdownNMs{ job=\"yarn_ressource_manager\"})",
     "legendFormat": "Shutdown"
    },
    {
     "expr": "max(Hadoop_ResourceManager_NumLostNMs{ job=\"yarn_ressource_manager\"})",
     "legendFormat": "Lost"
    }
   ]
  },
  { "title": "Cluster resources usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "YARN cluster memory utilization",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AvailableMB{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "max(Hadoop_ResourceManager_PendingMB{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedMB{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedMB{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "YARN cluster memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_PendingMB{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedMB{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedMB{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AvailableMB{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "YARN cluster vCores utilization",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AvailableVCores{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "max(Hadoop_ResourceManager_PendingVCores{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedVCores{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedVCores{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "YARN cluster vCores utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_PendingVCores{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedVCores{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedVCores{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AvailableVCores{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "YARN cluster apps stats",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AppsCompleted{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Completed"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AppsFailed{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AppsKilled{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Killed"
    }
   ]
  },
  {
   "title": "YARN cluster apps count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AppsPending{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AppsRunning{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "YARN cluster containers count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_PendingContainers{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedContainers{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedContainers{ job=\"yarn_ressource_manager\", q1=\"\"})",
     "legendFormat": "Allocated"
    }
   ]
  },
  { "title": "Queue resources usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "YARN queue memory utilization",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AvailableMB{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "max(Hadoop_ResourceManager_PendingMB{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedMB{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedMB{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "YARN queue memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_PendingMB{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedMB{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedMB{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AvailableMB{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "YARN queue vCores utilization",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AvailableVCores{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "max(Hadoop_ResourceManager_PendingVCores{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedVCores{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedVCores{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "YARN queue vCores utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_PendingVCores{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedVCores{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedVCores{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AvailableVCores{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "YARN queue apps stats",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AppsCompleted{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Completed"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AppsFailed{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AppsKilled{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Killed"
    }
   ]
  },
  {
   "title": "YARN queue apps count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AppsPending{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AppsRunning{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "YARN queue containers count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_PendingContainers{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedContainers{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedContainers{ job=\"yarn_ressource_manager\", q1=\"$queue\"})",
     "legendFormat": "Allocated"
    }
   ]
  }
 ]
}