{
 "title": "TDP zookeeper",
 "description": "Dashboard for TDP ZooKeeper (3.4.6) metrics generated by Prometheus JMX exporter",
 "tags": [
  "tdp",
  "zookeeper",
  "prometheus",
  "jmx",
  "tdp-custom"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "zookeeper_server" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "leader",
    "query": {
     "query": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_MaxSessionTimeout\",job=~\"$job\",name2=\"Leader\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NumAliveConnections",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_NumAliveConnections\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ZNodeCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_NodeCount\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{ instance }} ZNodeCount"
    }
   ]
  },
  {
   "title": "ZNodeCountRate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate({__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_NodeCount\",instance=~\"$instance\",job=~\"$job\"}[5m])",
     "legendFormat": "{{instance}} ZNodeCountRate"
    }
   ]
  },
  {
   "title": "QuorumSize",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max({__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_QuorumSize\",instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "QuorumSize"
    }
   ]
  },
  {
   "title": "Leader",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_MaxSessionTimeout\",instance=~\"$instance\",job=~\"$job\",name2=\"Leader\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LeaderUptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"java_lang_Runtime_Uptime\",instance=~\"$leader\",job=~\"$job\"}",
     "legendFormat": "{{instance}} Uptime"
    }
   ]
  },
  {
   "title": "PacketsReceived",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase({__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_PacketsReceived\",instance=~\"$instance\",job=~\"$job\", name3=\"\"}[1m])",
     "legendFormat": "{{instance}} PacketsReceived"
    }
   ]
  },
  {
   "title": "PacketsSent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase({__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_PacketsSent\",instance=~\"$instance\",job=~\"$job\", name3=\"\"}[1m])",
     "legendFormat": "{{instance}} PacketsSent"
    }
   ]
  },
  {
   "title": "QuorumUptime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"java_lang_Runtime_Uptime\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} Uptime"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NumAliveConnections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_NumAliveConnections\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} NumAliveConnections"
    }
   ]
  },
  {
   "title": "MinMaxAvgRequestLatency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_MaxRequestLatency\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} MaxRequestLatency"
    },
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_MinRequestLatency\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} MinRequestLatency"
    },
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_AvgRequestLatency\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} AvgRequestLatency"
    }
   ]
  },
  {
   "title": "WatchCount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_WatchCount\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}} WatchCount"
    }
   ]
  },
  {
   "title": "OutstandingRequests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"org_apache_ZooKeeperService_ReplicatedServer_.*_OutstandingRequests\",instance=~\"$instance\",job=~\"$job\", name3=\"\"}",
     "legendFormat": "{{instance}} OutstandingRequests"
    }
   ]
  }
 ]
}