{
 "title": "TDP Hive",
 "description": "Dashboard for TDP Hive service generated by Prometheus exporters",
 "tags": [
  "tdp",
  "hive",
  "prometheus",
  "jmx",
  "tdp-custom"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Components status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hive Metastores heap (JVM)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_heap_used_Value{ job=\"hive_metastore\"}",
     "legendFormat": "{{ instance }} heap used"
    },
    {
     "expr": "avg(metrics_heap_max_Value{ job=\"hive_metastore\"})",
     "legendFormat": "Max heap"
    },
    {
     "expr": "avg(metrics_heap_max_Value{ job=\"hive_metastore\"})*1.1",
     "legendFormat": "MaxGraph"
    }
   ]
  },
  {
   "title": "Hive Server2s heap (JVM)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "metrics_memory_heap_used_Value{ job=\"hive_server2s\"}",
     "legendFormat": "{{ instance }} heap used"
    },
    {
     "expr": "avg(metrics_memory_heap_max_Value{ job=\"hive_server2s\"})",
     "legendFormat": "Max heap"
    },
    {
     "expr": "avg(metrics_memory_heap_max_Value{ job=\"hive_server2s\"})*1.1",
     "legendFormat": "MaxGraph"
    }
   ]
  },
  { "title": "Hive warehouse metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Hive databases count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max(metrics_total_count_dbs_Value{ job=\"hive_metastore\"})",
     "legendFormat": "Databases"
    }
   ]
  },
  {
   "title": "Hive tables count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "max(metrics_total_count_tables_Value{ job=\"hive_metastore\"})",
     "legendFormat": "Tables"
    }
   ]
  },
  {
   "title": "Hive partitions count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "max(metrics_total_count_partitions_Value{ job=\"hive_metastore\"})",
     "legendFormat": "Tables"
    }
   ]
  },
  { "title": "Hive performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Hive Server2s sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "metrics_hs2_open_sessions_Value{ job=\"hive_server2s\"}",
     "legendFormat": "Open on {{ instance }}"
    },
    {
     "expr": "metrics_hs2_active_sessions_Value{ job=\"hive_server2s\"}",
     "legendFormat": "Active on {{ instance }}"
    }
   ]
  },
  {
   "title": "Hive Server2s connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "metrics_open_connections_Count{ job=\"hive_server2s\"}",
     "legendFormat": "Open on {{ instance }}"
    }
   ]
  },
  {
   "title": "Hive Metastores connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "metrics_open_connections_Value{ job=\"hive_metastore\"}",
     "legendFormat": "Open on {{ instance }}"
    }
   ]
  }
 ]
}