{
 "title": "TDP HBase",
 "description": "Dashboard for TDP HBase service generated by Prometheus exporters",
 "tags": [
  "tdp",
  "hbase",
  "prometheus",
  "jmx",
  "tdp-custom"
 ],
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "service", "query": "hbase" },
   {
    "name": "activeHM",
    "query": {
     "query": "query_result(Hadoop_HBase_masterActiveTime{ service=\"$service\"} > 0)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Components status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HBase Active Master",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_HBase_masterActiveTime{instance=\"$activeHM\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Hbase Masters heap (JVM)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "Hadoop_HBase_MemHeapUsedM{job=\"hbase_master\"}",
     "legendFormat": "{{ instance }} heap used"
    },
    {
     "expr": "avg(Hadoop_HBase_MemHeapMaxM{job=\"hbase_master\"})",
     "legendFormat": "Max heap"
    },
    {
     "expr": "avg(Hadoop_HBase_MemHeapMaxM{ job=\"hbase_master\"})*1.1",
     "legendFormat": "MaxGraph"
    }
   ]
  },
  {
   "title": "HBase RegionServers status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_HBase_numRegionServers{ job=\"hbase_master\", instance=\"$activeHM\"}-Hadoop_HBase_numDeadRegionServers{ job=\"hbase_master\", instance=\"$activeHM\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "Hadoop_HBase_numDeadRegionServers{ job=\"hbase_master\", instance=\"$activeHM\"}",
     "legendFormat": "Dead"
    }
   ]
  },
  { "title": "HBase performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "HBase hosted regions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_HBase_regionCount{ job=\"hbase_region_server\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HBase regions in transit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "Hadoop_HBase_ritCount{ job=\"hbase_master\"}",
     "legendFormat": "Regions in transit"
    },
    {
     "expr": "Hadoop_HBase_ritCountOverThreshold{ job=\"hbase_master\"}",
     "legendFormat": "Regions in transit over duration threshold"
    }
   ]
  },
  {
   "title": "HBase regions transit duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "Hadoop_HBase_RitDuration_mean{ job=\"hbase_master\"}",
     "legendFormat": "Avg transit duration"
    },
    {
     "expr": "Hadoop_HBase_RitDuration_max{ job=\"hbase_master\"}",
     "legendFormat": "Max transit duration"
    },
    {
     "expr": "Hadoop_HBase_RitDuration_min{ job=\"hbase_master\"}",
     "legendFormat": "Min transit duration"
    }
   ]
  },
  {
   "title": "HBase RegionServers open connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_HBase_numOpenConnections{ job=\"hbase_region_server\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HBase RegionServers requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(Hadoop_HBase_readRequestCount{ job=\"hbase_region_server\"}[1m]))",
     "legendFormat": "Read requests / sec"
    },
    {
     "expr": "sum(increase(Hadoop_HBase_writeRequestCount{ job=\"hbase_region_server\"}[1m]))",
     "legendFormat": "Write requests / sec"
    }
   ]
  },
  {
   "title": "HBase RegionServers cache hit percent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(Hadoop_HBase_blockCacheExpressHitPercent{ job=\"hbase_region_server\"})",
     "legendFormat": "Read requests"
    }
   ]
  },
  {
   "title": "HBase RegionServers operations mean latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_HBase_Append_mean{ job=\"hbase_region_server\"})",
     "legendFormat": "Append"
    },
    {
     "expr": "avg(Hadoop_HBase_Delete_mean{ job=\"hbase_region_server\"})",
     "legendFormat": "Delete"
    },
    {
     "expr": "avg(Hadoop_HBase_Get_mean{ job=\"hbase_region_server\"})",
     "legendFormat": "Get"
    },
    {
     "expr": "avg(Hadoop_HBase_Replay_mean{ job=\"hbase_region_server\"})",
     "legendFormat": "Replay"
    },
    {
     "expr": "avg(Hadoop_HBase_Increment_mean{ job=\"hbase_region_server\"})",
     "legendFormat": "Increment"
    }
   ]
  },
  {
   "title": "HBase RegionServers operations p99 latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_HBase_Append_99th_percentile{ job=\"hbase_region_server\"})",
     "legendFormat": "Append"
    },
    {
     "expr": "avg(Hadoop_HBase_Delete_99th_percentile{ job=\"hbase_region_server\"})",
     "legendFormat": "Delete"
    },
    {
     "expr": "avg(Hadoop_HBase_Get_99th_percentile{ job=\"hbase_region_server\"})",
     "legendFormat": "Get"
    },
    {
     "expr": "avg(Hadoop_HBase_Replay_99th_percentile{ job=\"hbase_region_server\"})",
     "legendFormat": "Replay"
    },
    {
     "expr": "avg(Hadoop_HBase_Increment_99th_percentile{ job=\"hbase_region_server\"})",
     "legendFormat": "Increment"
    }
   ]
  },
  {
   "title": "HBase RegionServers slow operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(increase(Hadoop_HBase_slowAppendCount{ job=\"hbase_region_server\"}[1m]))",
     "legendFormat": "Append"
    },
    {
     "expr": "avg(increase(Hadoop_HBase_slowDeleteCount{ job=\"hbase_region_server\"}[1m]))",
     "legendFormat": "Delete"
    },
    {
     "expr": "avg(increase(Hadoop_HBase_slowGetCount{ job=\"hbase_region_server\"}[1m]))",
     "legendFormat": "Get"
    },
    {
     "expr": "avg(increase(Hadoop_HBase_slowReplayCount{ job=\"hbase_region_server\"}[1m]))",
     "legendFormat": "Replay"
    },
    {
     "expr": "avg(increase(Hadoop_HBase_slowIncrementCount{ job=\"hbase_region_server\"}[1m]))",
     "legendFormat": "Increment"
    }
   ]
  },
  {
   "title": "HBase RegionServers compaction queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_HBase_compactionQueueLength{ job=\"hbase_region_server\"})",
     "legendFormat": "Compactions"
    }
   ]
  },
  {
   "title": "HBase RegionServers major/minor compactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(Hadoop_HBase_CompactionTime_num_ops{ job=\"hbase_region_server\"}[1m]))",
     "legendFormat": "Compactions"
    }
   ]
  },
  {
   "title": "HBase RegionServers major compactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(Hadoop_HBase_MajorCompactionTime_num_ops{ job=\"hbase_region_server\"}[1m]))",
     "legendFormat": "Compactions"
    }
   ]
  }
 ]
}