# Copyright 2022 TOSIT.IO
# Copyright 2017-2018 Pawel Krupa, Roman Demachkovych
# SPDX-License-Identifier: Apache-2.0 AND MIT
# Copied and adapted from https://github.com/cloudalchemy/ansible-grafana.git
---
- name: Ensure grafana configuration directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: "{{ grafana_group }}"
    mode: "775"
  with_items:
    - "/etc/grafana"
    - "/etc/grafana/datasources"
    - "/etc/grafana/provisioning"
    - "/etc/grafana/provisioning/datasources"
    - "/etc/grafana/provisioning/dashboards"
    - "/etc/grafana/provisioning/notifiers"
    - "/etc/grafana/provisioning/plugins"

- name: Create grafana main configuration file
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: "{{ grafana_group }}"
    mode: "640"
  no_log: "{{ false if (lookup('env', 'CI')) or (lookup('env', 'MOLECULE_PROVISIONER_NAME')) else true }}"

- name: Create grafana LDAP configuration file
  ansible.builtin.template:
    src: ldap.toml.j2
    dest: "{{ grafana_auth.ldap.config_file | default('/etc/grafana/ldap.toml') }}"
    owner: root
    group: "{{ grafana_group }}"
    mode: "640"
  when:
    - "'ldap' in grafana_auth"
    - "'enabled' not in grafana_auth.ldap or grafana_auth.ldap.enabled"
  no_log: true

- name: Create grafana directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "750"
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
  with_items:
    - "{{ grafana_logs_dir }}"
    - "{{ grafana_data_dir }}"
    - "{{ grafana_data_dir }}/dashboards"
    - "{{ grafana_data_dir }}/plugins"

- name: Manage grafana socket directory
  when:
    - grafana_server.protocol is defined and grafana_server.protocol == 'socket'
    - grafana_server.socket | dirname != '/var/run'
  block:
    - name: Create grafana socket directory
      ansible.builtin.file:
        path: "{{ grafana_server.socket | dirname }}"
        state: directory
        mode: "775"
        owner: "{{ grafana_user }}"
        group: "{{ grafana_group }}"

    - name: Ensure grafana socket directory created on startup
      ansible.builtin.template:
        src: tmpfiles.j2
        dest: /etc/tmpfiles.d/grafana.conf
        owner: root
        group: root
        mode: "644"

- name: Enable grafana to ports lower than port 1024
  community.general.capabilities:
    path: /usr/sbin/grafana-server
    capability: CAP_NET_BIND_SERVICE+ep
    state: present
  when:
    - grafana_port | int <= 1024
    - grafana_cap_net_bind_service
