# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Run preflight checks
  ansible.builtin.include_tasks:
    file: preflight.yml

- name: Create Grafana certs dir
  ansible.builtin.file:
    path: "{{ grafana_certs_dir }}"
    state: directory
    owner: root
    group: "{{ grafana_group }}"
    mode: "0770"

- name: Copy node certificates to Grafana certs dir
  ansible.builtin.copy:
    src: "/etc/ssl/certs/{{ ansible_fqdn }}.{{ item }}"
    dest: "{{ grafana_certs_dir }}/{{ ansible_fqdn }}.{{ item }}"
    remote_src: true
    owner: root
    group: "{{ grafana_group }}"
    mode: "0640"
  loop:
    - pem
    - key

- name: Configure grafana
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Install plugins
  ansible.builtin.include_tasks:
    file: plugins.yml
  when: (grafana_plugins | length)

- name: Install datasources
  ansible.builtin.include_tasks:
    file: datasources.yml
  when: (grafana_datasources | length)

- name: Install notifications
  ansible.builtin.include_tasks:
    file: notifications.yml
  when: (grafana_alert_notifications | length)

- name: Install dashboards
  ansible.builtin.include_tasks:
    file: dashboards.yml
