# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Wait for grafana to start (http/s)
  ansible.builtin.wait_for:
    host: "{{ grafana_address }}"
    port: "{{ grafana_port }}"
  when: grafana_server.protocol is undefined or grafana_server.protocol in ['http', 'https']

- ansible.builtin.include_role:
    name: cloudalchemy.grafana
    tasks_from: datasources
  when: (grafana_datasources | length)

- ansible.builtin.include_role:
    name: cloudalchemy.grafana
    tasks_from: notifications
  when: (grafana_alert_notifications | length)

- name: "Check if there are any dashboards in local {{ grafana_dashboards_dir }}"
  become: false
  ansible.builtin.set_fact:
    found_dashboards: "{{ lookup('fileglob', grafana_dashboards_dir + '/*.json', wantlist=True) }}"

- ansible.builtin.include_role:
    name: cloudalchemy.grafana
    tasks_from: dashboards
  when: (grafana_dashboards | length) or (found_dashboards | length)
