# Copyright 2022 TOSIT.IO
# Copyright 2017-2018 Pawel Krupa, Roman Demachkovych
# SPDX-License-Identifier: Apache-2.0 AND MIT
# Copied and adapted from https://github.com/cloudalchemy/ansible-grafana.git
---
- name: Create/Delete/Update alert notifications channels (provisioning)
  become: true
  ansible.builtin.copy:
    content: |
      apiVersion: 1
      {{ grafana_alert_notifications | to_nice_yaml }}
    dest: /etc/grafana/provisioning/notifiers/ansible.yml
    owner: root
    group: "{{ grafana_group }}"
    mode: "640"
  when: grafana_use_provisioning
