# Copyright 2022 TOSIT.IO
# Copyright 2017-2018 Pawel Krupa, Roman Demachkovych
# SPDX-License-Identifier: Apache-2.0 AND MIT
# Copied and adapted from https://github.com/cloudalchemy/ansible-grafana.git
---
- name: Check which plugins are installed
  ansible.builtin.find:
    file_type: directory
    recurse: false
    paths: "{{ grafana_data_dir }}/plugins"
  register: installed_plugins

- name: Install plugins
  become: true
  ansible.builtin.command: "grafana-cli --pluginsDir {{ grafana_data_dir }}/plugins plugins install {{ item }}"
  args:
    creates: "{{ grafana_data_dir }}/plugins/{{ item }}"
  with_items: "{{ grafana_plugins | difference(installed_plugins.files) }}"
  register: _plugin_install
  until: _plugin_install is succeeded
  retries: 5
  delay: 2
