# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Start Grafana server
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: "{{ grafana_start_on_boot }}"
