# Copyright 2022 Adaltas
# SPDX-License-Identifier: MIT

---
- name: Start Grafana server
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: "{{ grafana_start_on_boot }}"
