# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- ansible.builtin.import_playbook: ../exporter_node_install.yml
# exporter_install
- ansible.builtin.import_playbook: ../exporter_node_config.yml
# exporter_config
- ansible.builtin.import_playbook: ../exporter_node_start.yml
# exporter_start
# exporter_init
