# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- import_playbook: ../exporter_node_install.yml
- import_playbook: ../exporter_postgres_install.yml
# exporter_node_config
- import_playbook: ../exporter_node_start.yml
# exporter_postgres_config
- import_playbook: ../exporter_postgres_start.yml
