# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- ansible.builtin.import_playbook: ../exporter_node_install.yml
- ansible.builtin.import_playbook: ../exporter_node_config.yml
- ansible.builtin.import_playbook: ../exporter_node_start.yml
