# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- ansible.builtin.import_playbook: ../prometheus_server_install.yml
# prometheus_install
- ansible.builtin.import_playbook: ../prometheus_server_config.yml
# prometheus_config
- ansible.builtin.import_playbook: ../prometheus_server_start.yml
# prometheus_start
# prometheus_init
