{
 "title": "TDP HBase",
 "description": "Dashboard for TDP HBase service generated by Prometheus exporters",
 "tags": [
  "tdp",
  "hbase",
  "prometheus",
  "jmx"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "service", "query": "HBase" },
   {
    "name": "activeHM",
    "query": {
     "query": "query_result(Hadoop_HBase_masterActiveTime{cluster=\"$cluster\", service=\"$service\"} > 0)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Components status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HBase Masters status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\",job=\"hbase_master\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HBase REST Servers status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\",job=\"hbase_rest\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Phoenix Query Servers status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\",job=\"phoenix_queryserver\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HBase RegionServers status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\",job=\"hbase_rs\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HBase Active Master",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_HBase_masterActiveTime{instance=\"$activeHM\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Hbase Masters heap (JVM)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "Hadoop_HBase_MemHeapUsedM{cluster=\"$cluster\", job=\"hbase_master\"}",
     "legendFormat": "{{ instance }} heap used"
    },
    {
     "expr": "avg(Hadoop_HBase_MemHeapMaxM{cluster=\"$cluster\", job=\"hbase_master\"})",
     "legendFormat": "Max heap"
    },
    {
     "expr": "avg(Hadoop_HBase_MemHeapMaxM{cluster=\"$cluster\", job=\"hbase_master\"})*1.1",
     "legendFormat": "MaxGraph"
    }
   ]
  },
  {
   "title": "HBase RegionServers status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_HBase_numRegionServers{cluster=\"$cluster\", job=\"hbase_master\", instance=\"$activeHM\"}-Hadoop_HBase_numDeadRegionServers{cluster=\"$cluster\", job=\"hbase_master\", instance=\"$activeHM\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "Hadoop_HBase_numDeadRegionServers{cluster=\"$cluster\", job=\"hbase_master\", instance=\"$activeHM\"}",
     "legendFormat": "Dead"
    }
   ]
  },
  { "title": "HBase performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "HBase hosted regions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_HBase_regionCount{cluster=\"$cluster\", job=\"hbase_rs\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HBase regions in transit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "Hadoop_HBase_ritCount{cluster=\"$cluster\", job=\"hbase_master\"}",
     "legendFormat": "Regions in transit"
    },
    {
     "expr": "Hadoop_HBase_ritCountOverThreshold{cluster=\"$cluster\", job=\"hbase_master\"}",
     "legendFormat": "Regions in transit over duration threshold"
    }
   ]
  },
  {
   "title": "HBase regions transit duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "Hadoop_HBase_RitDuration_mean{cluster=\"$cluster\", job=\"hbase_master\"}",
     "legendFormat": "Avg transit duration"
    },
    {
     "expr": "Hadoop_HBase_RitDuration_max{cluster=\"$cluster\", job=\"hbase_master\"}",
     "legendFormat": "Max transit duration"
    },
    {
     "expr": "Hadoop_HBase_RitDuration_min{cluster=\"$cluster\", job=\"hbase_master\"}",
     "legendFormat": "Min transit duration"
    }
   ]
  },
  {
   "title": "HBase RegionServers open connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_HBase_numOpenConnections{cluster=\"$cluster\", job=\"hbase_rs\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HBase RegionServers requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(Hadoop_HBase_readRequestCount{cluster=\"$cluster\", job=\"hbase_rs\"}[1m]))",
     "legendFormat": "Read requests / sec"
    },
    {
     "expr": "sum(increase(Hadoop_HBase_writeRequestCount{cluster=\"$cluster\", job=\"hbase_rs\"}[1m]))",
     "legendFormat": "Write requests / sec"
    }
   ]
  },
  {
   "title": "HBase RegionServers cache hit percent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(Hadoop_HBase_blockCacheExpressHitPercent{cluster=\"$cluster\", job=\"hbase_rs\"})",
     "legendFormat": "Read requests"
    }
   ]
  },
  {
   "title": "HBase RegionServers operations mean latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_HBase_Append_mean{cluster=\"$cluster\", job=\"hbase_rs\"})",
     "legendFormat": "Append"
    },
    {
     "expr": "avg(Hadoop_HBase_Delete_mean{cluster=\"$cluster\", job=\"hbase_rs\"})",
     "legendFormat": "Delete"
    },
    {
     "expr": "avg(Hadoop_HBase_Get_mean{cluster=\"$cluster\", job=\"hbase_rs\"})",
     "legendFormat": "Get"
    },
    {
     "expr": "avg(Hadoop_HBase_Replay_mean{cluster=\"$cluster\", job=\"hbase_rs\"})",
     "legendFormat": "Replay"
    },
    {
     "expr": "avg(Hadoop_HBase_Increment_mean{cluster=\"$cluster\", job=\"hbase_rs\"})",
     "legendFormat": "Increment"
    }
   ]
  },
  {
   "title": "HBase RegionServers operations p99 latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_HBase_Append_99th_percentile{cluster=\"$cluster\", job=\"hbase_rs\"})",
     "legendFormat": "Append"
    },
    {
     "expr": "avg(Hadoop_HBase_Delete_99th_percentile{cluster=\"$cluster\", job=\"hbase_rs\"})",
     "legendFormat": "Delete"
    },
    {
     "expr": "avg(Hadoop_HBase_Get_99th_percentile{cluster=\"$cluster\", job=\"hbase_rs\"})",
     "legendFormat": "Get"
    },
    {
     "expr": "avg(Hadoop_HBase_Replay_99th_percentile{cluster=\"$cluster\", job=\"hbase_rs\"})",
     "legendFormat": "Replay"
    },
    {
     "expr": "avg(Hadoop_HBase_Increment_99th_percentile{cluster=\"$cluster\", job=\"hbase_rs\"})",
     "legendFormat": "Increment"
    }
   ]
  },
  {
   "title": "HBase RegionServers slow operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(increase(Hadoop_HBase_slowAppendCount{cluster=\"$cluster\", job=\"hbase_rs\"}[1m]))",
     "legendFormat": "Append"
    },
    {
     "expr": "avg(increase(Hadoop_HBase_slowDeleteCount{cluster=\"$cluster\", job=\"hbase_rs\"}[1m]))",
     "legendFormat": "Delete"
    },
    {
     "expr": "avg(increase(Hadoop_HBase_slowGetCount{cluster=\"$cluster\", job=\"hbase_rs\"}[1m]))",
     "legendFormat": "Get"
    },
    {
     "expr": "avg(increase(Hadoop_HBase_slowReplayCount{cluster=\"$cluster\", job=\"hbase_rs\"}[1m]))",
     "legendFormat": "Replay"
    },
    {
     "expr": "avg(increase(Hadoop_HBase_slowIncrementCount{cluster=\"$cluster\", job=\"hbase_rs\"}[1m]))",
     "legendFormat": "Increment"
    }
   ]
  },
  {
   "title": "HBase RegionServers compaction queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_HBase_compactionQueueLength{cluster=\"$cluster\", job=\"hbase_rs\"})",
     "legendFormat": "Compactions"
    }
   ]
  },
  {
   "title": "HBase RegionServers major/minor compactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(Hadoop_HBase_CompactionTime_num_ops{cluster=\"$cluster\", job=\"hbase_rs\"}[1m]))",
     "legendFormat": "Compactions"
    }
   ]
  },
  {
   "title": "HBase RegionServers major compactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(Hadoop_HBase_MajorCompactionTime_num_ops{cluster=\"$cluster\", job=\"hbase_rs\"}[1m]))",
     "legendFormat": "Compactions"
    }
   ]
  }
 ]
}