{
 "title": "TDP YARN",
 "description": "Dashboard for TDP YARN service generated by Prometheus exporters",
 "tags": [
  "tdp",
  "yarn",
  "prometheus",
  "jmx"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "service", "query": "YARN" },
   {
    "name": "queue",
    "label": "Queue",
    "query": {
     "query": "label_values({cluster=\"$cluster\", service=\"$service\"}, q1)"
    }
   },
   {
    "name": "activeRM",
    "query": {
     "query": "query_result(Hadoop_ResourceManager_NumActiveNMs{cluster=\"$cluster\", service=\"$service\"} > 0)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Components status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "YARN ResourceManagers status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\",job=\"yarn_rm\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "YARN ResourceManagers status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\",job=\"yarn_rm\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MapReduce Job History Servers status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\",job=\"mapred_jhs\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "YARN NodeManagers status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\",job=\"yarn_nm\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "YARN Active ResourceManager",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_NumActiveNMs{instance=\"$activeRM\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "YARN ResourceManagers heap (JVM)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "Hadoop_ResourceManager_MemHeapUsedM{cluster=\"$cluster\", job=\"yarn_rm\"}",
     "legendFormat": "{{ instance }} heap used"
    },
    {
     "expr": "avg(Hadoop_ResourceManager_MemHeapMaxM{cluster=\"$cluster\", job=\"yarn_rm\"})",
     "legendFormat": "Max heap"
    },
    {
     "expr": "avg(Hadoop_ResourceManager_MemHeapMaxM{cluster=\"$cluster\", job=\"yarn_rm\"})*1.1",
     "legendFormat": "MaxGraph"
    }
   ]
  },
  {
   "title": "YARN NodeManagers status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_NumActiveNMs{cluster=\"$cluster\", job=\"yarn_rm\"})",
     "legendFormat": "Active"
    },
    {
     "expr": "max(Hadoop_ResourceManager_NumUnhealthyNMs{cluster=\"$cluster\", job=\"yarn_rm\"})",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "max(Hadoop_ResourceManager_NumShutdownNMs{cluster=\"$cluster\", job=\"yarn_rm\"})",
     "legendFormat": "Shutdown"
    },
    {
     "expr": "max(Hadoop_ResourceManager_NumLostNMs{cluster=\"$cluster\", job=\"yarn_rm\"})",
     "legendFormat": "Lost"
    }
   ]
  },
  { "title": "Cluster resources usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "YARN cluster memory utilization",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AvailableMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "max(Hadoop_ResourceManager_PendingMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "YARN cluster memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_PendingMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AvailableMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "YARN cluster vCores utilization",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AvailableVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "max(Hadoop_ResourceManager_PendingVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "YARN cluster vCores utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_PendingVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AvailableVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "YARN cluster apps stats",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AppsCompleted{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Completed"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AppsFailed{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AppsKilled{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Killed"
    }
   ]
  },
  {
   "title": "YARN cluster apps count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AppsPending{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AppsRunning{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "YARN cluster containers count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_PendingContainers{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedContainers{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedContainers{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"\"})",
     "legendFormat": "Allocated"
    }
   ]
  },
  { "title": "Queue resources usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "YARN queue memory utilization",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AvailableMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "max(Hadoop_ResourceManager_PendingMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "YARN queue memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_PendingMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AvailableMB{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "YARN queue vCores utilization",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AvailableVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "max(Hadoop_ResourceManager_PendingVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Reserved"
    }
   ]
  },
  {
   "title": "YARN queue vCores utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_PendingVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AvailableVCores{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "YARN queue apps stats",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AppsCompleted{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Completed"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AppsFailed{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AppsKilled{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Killed"
    }
   ]
  },
  {
   "title": "YARN queue apps count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_AppsPending{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AppsRunning{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "YARN queue containers count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(Hadoop_ResourceManager_PendingContainers{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "max(Hadoop_ResourceManager_ReservedContainers{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "max(Hadoop_ResourceManager_AllocatedContainers{cluster=\"$cluster\", job=\"yarn_rm\", q1=\"$queue\"})",
     "legendFormat": "Allocated"
    }
   ]
  }
 ]
}