{
 "title": "TDP Cluster Overview",
 "description": "Dashboard for TDP Cluster overview generated by Prometheus exporters",
 "tags": [
  "tdp",
  "cluster",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Cluster overall status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"exporter_node\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Services status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service) (up{service!~\"(exporter|)\"})*100",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "ZooKeeper status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "ZooKeeper Servers status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"zookeeper_server\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "HDFS status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "HDFS NameNodes status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"hdfs_namenode\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "HDFS ZooKeeper Failover Controllers status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"hdfs_namenode_zkfc\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "HDFS JournalNodes status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"hdfs_journal_node\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "HDFS DataNodes status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"hdfs_datanode\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "YARN status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "YARN ResourceManagers status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"yarn_ressource_manager\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "YARN Timeline Server status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"yarn_timeline_server\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "MapReduce Job History Servers status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"yarn_mapred_history_server\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "YARN NodeManagers status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"yarn_node_manager\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "HBase status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "HBase Masters status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"hbase_master\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "HBase REST Servers status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"hbase_rest\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Phoenix Query Servers status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"hbase_phoenix_queryserver_daemon\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "HBase RegionServers status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"hbase_region_server\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hive status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hive Metastores status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"hive_metastore\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Hive Server2s status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"hive_server2s\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ranger status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ranger Admin Servers status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"ranger_admin\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Ranger Usersync Servers status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"ranger_usersync\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Ranger Key Management Service",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"ranger_key_management_service\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Knox status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Knox Servers status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"knox_gateway\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}