{
 "title": "TDP HDFS",
 "tags": [
  "tdp",
  "hdfs",
  "prometheus",
  "jmx"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=~\"hdfs.*\"}, instance)"
    }
   },
   {
    "name": "ActiveNameNode",
    "query": {
     "query": "query_result(Hadoop_NameNode_MillisSinceLastLoadedEdits{ job=\"hdfs_namenode\"} == 0) "
    }
   }
  ]
 },
 "panels": [
  { "title": "HDFS Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HDFS NameNodes status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"hdfs_namenode\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HDFS JournalNodes status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"hdfs_journal_node\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HDFS ZooKeeper Failover Controllers status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"hdfs_namenode_zkfc\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HDFS DataNodes status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"hdfs_datanode\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "NumAliveConnections",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_NumOpenConnections{job=~\"hdfs_namenode\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active NameNode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_MillisSinceLastLoadedEdits{ job=\"hdfs_namenode\"} == 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HDFS NameNode heap (JVM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_MemHeapUsedM{ job=\"hdfs_namenode\"}",
     "legendFormat": "{{ instance }} heap used"
    },
    {
     "expr": "avg(Hadoop_NameNode_MemHeapMaxM{ job=\"hdfs_namenode\"})",
     "legendFormat": "Max heap"
    },
    {
     "expr": "avg(Hadoop_NameNode_MemHeapMaxM{ job=\"hdfs_namenode\"})*1.1",
     "legendFormat": "MaxGraph"
    }
   ]
  },
  {
   "title": "Active NameNode Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{instance=~\"$ActiveNameNode\",job=~\"hdfs_namenode\"}",
     "legendFormat": "{{instance}} Uptime"
    }
   ]
  },
  { "title": "NameNode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "NameNode Used Capacity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100*(Hadoop_NameNode_CapacityUsed{job=~\"hdfs_namenode\",name=\"FSNamesystem\"}/Hadoop_NameNode_CapacityTotal{job=~\"hdfs_namenode\",name=\"FSNamesystem\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NameNode Total Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_BlocksTotal{job=~\"hdfs_namenode\",name=\"FSNamesystemState\"}",
     "legendFormat": "{{instance}} Blocks"
    }
   ]
  },
  {
   "title": "NameNode Capacity Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_CapacityUsed{job=~\"hdfs_namenode\",name=\"FSNamesystem\"}/(1024*1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Corrupted or Under Replicated Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Hadoop_NameNode_CorruptBlocks{job=~\"hdfs_namenode\"}",
     "legendFormat": "{{instance}} corrupt blocks"
    },
    {
     "expr": "Hadoop_NameNode_UnderReplicatedBlocks{job=~\"hdfs_namenode\", name=\"FSNamesystem\",}",
     "legendFormat": "{{instance}}  under replicated blocks"
    }
   ]
  },
  {
   "title": "NameNode JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "OpenFileDescriptorCount",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{job=~\"hdfs_namenode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jvm_classes_loaded",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(jvm_classes_loaded{job=~\"hdfs_namenode\"})"
      }
     ]
    },
    {
     "title": "jvm_threads_current",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(jvm_threads_current{job=~\"hdfs_namenode\"})"
      }
     ]
    },
    {
     "title": "jvm_threads_deadlocked",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(jvm_threads_deadlocked{job=~\"hdfs_namenode\"})"
      }
     ]
    },
    {
     "title": "jvm_memory_pool_bytes_used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{job=~\"hdfs_namenode\"}",
       "legendFormat": "{{instance}} pool:{{pool}}"
      }
     ]
    },
    {
     "title": "jvm_gc_collection_seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"hdfs_namenode\"}[5m])",
       "legendFormat": "{{instance}} gc:{{gc}}"
      }
     ]
    },
    {
     "title": "jvm_threads_state",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_state{job=~\"hdfs_namenode\"}",
       "legendFormat": "{{instance}} state:{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JournalNode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "JournalNode Alive Connections",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "Hadoop_JournalNode_NumOpenConnections{job=~\"hdfs_journal_node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JournalNode Operations per minutes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(Hadoop_JournalNode_JournalNumOps{job=~\"hdfs_journal_node\"}[1m])",
       "legendFormat": "{{instance}} ops"
      }
     ]
    },
    {
     "title": "JournalNode Batches Writen per minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "yaxes": [
      { "format": "opm" }
     ],
     "targets": [
      {
       "expr": "rate(Hadoop_JournalNode_BatchesWritten{job=~\"hdfs_journal_node\"}[1m])",
       "legendFormat": "{{instance}} batches"
      }
     ]
    },
    {
     "title": "Queue Length",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "Hadoop_JournalNode_CallQueueLength{job=~\"hdfs_journal_node\"}",
       "legendFormat": "{{instance}} queue"
      }
     ]
    },
    {
     "title": "JournalNode Operations Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "Hadoop_JournalNode_JournalAvgTime{job=~\"hdfs_journal_node\"}",
       "legendFormat": "{{instance}} latency"
      }
     ]
    },
    {
     "title": "JournalNode Batches Lagging",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "Hadoop_JournalNode_BatchesWrittenWhileLagging{job=~\"hdfs_journal_node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JournalNode JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "OpenFileDescriptorCount",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{job=~\"hdfs_journal_node\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jvm_classes_loaded",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(jvm_classes_loaded{job=~\"hdfs_journal_node\"})"
      }
     ]
    },
    {
     "title": "jvm_threads_current",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(jvm_threads_current{job=~\"hdfs_journal_node\"})"
      }
     ]
    },
    {
     "title": "jvm_threads_deadlocked",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(jvm_threads_deadlocked{job=~\"hdfs_journal_node\"})"
      }
     ]
    },
    {
     "title": "jvm_memory_pool_bytes_used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{job=~\"hdfs_journal_node\"}",
       "legendFormat": "{{instance}} pool:{{pool}}"
      }
     ]
    },
    {
     "title": "jvm_gc_collection_seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"hdfs_journal_node\"}[5m])",
       "legendFormat": "{{instance}} gc:{{gc}}"
      }
     ]
    },
    {
     "title": "jvm_threads_state",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_state{job=~\"hdfs_journal_node\"}",
       "legendFormat": "{{instance}} state:{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DataNode",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "DataNode Used Capacity",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100*(Hadoop_DataNode_DfsUsed{ job=\"hdfs_datanode\",name=\"FSDatasetState\",}/Hadoop_DataNode_Capacity{ job=\"hdfs_datanode\",name=\"FSDatasetState\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DataNode Reads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_ReadIoRateNumOps{ job=\"hdfs_datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DataNode Writes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_WriteIoRateNumOps{ job=\"hdfs_datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DataNode Stored Data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_DfsUsed{ job=\"hdfs_datanode\",name=\"FSDatasetState\",}/(1024*1024)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DataNode Reads Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_ReadIoRateAvgTime{ job=\"hdfs_datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DataNode Writes Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "Hadoop_DataNode_WriteIoRateAvgTime{job=\"hdfs_datanode\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "DataNode JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "OpenFileDescriptorCount",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{job=~\"hdfs_datanode\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_classes_loaded",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_classes_loaded{instance=~\"$instance\",job=~\"hdfs_datanode\"})"
    }
   ]
  },
  {
   "title": "jvm_threads_current",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_threads_current{job=~\"hdfs_datanode\"})"
    }
   ]
  },
  {
   "title": "jvm_threads_deadlocked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_threads_deadlocked{job=~\"hdfs_datanode\"})"
    }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"hdfs_datanode\"}",
     "legendFormat": "{{instance}} pool:{{pool}}"
    }
   ]
  },
  {
   "title": "jvm_threads_state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{job=~\"hdfs_datanode\"}",
     "legendFormat": "{{instance}} state:{{state}}"
    }
   ]
  },
  {
   "title": "jvm_gc_collection_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"hdfs_datanode\"}[5m])",
     "legendFormat": "{{instance}} gc:{{gc}}"
    }
   ]
  }
 ]
}