# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: node-exporter restart
  hosts: exporter_node
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: exporter_node
    - name: Restart node exporter
      ansible.builtin.import_role:
        name: tosit.tdp_observability.exporter.node
        tasks_from: restart
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
