# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: postgres-exporter start
  hosts: exporter_postgres
  tasks:
    - tosit.tdp.resolve: # noqa unnamed-task
        node_name: exporter_postgres
    - name: Start postgres exporter
      ansible.builtin.import_role:
        name: tosit.tdp_observability.exporter.postgres
        tasks_from: start
    - ansible.builtin.meta: clear_facts # noqa unnamed-task
