# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Loki server start
  hosts: loki
  tasks:
    - tosit.tdp.resolve:                # noqa name[missing]
        node_name: loki_server
    - name: Start loki server
      ansible.builtin.import_role:
        name: tosit.tdp_observability.loki.server
        tasks_from: start
    - ansible.builtin.meta: clear_facts # noqa name[missing]
