# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Loki server start
  hosts: loki
  tasks:
    - tosit.tdp.resolve:
        node_name: loki_server
    - import_role:
        name: tosit.tdp_observability.loki.server
        tasks_from: start
    - meta: clear_facts
