# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Loki Promtail config
  hosts: promtail
  tasks:
    - tosit.tdp.resolve:                # noqa name[missing]
        node_name: loki_promtail
    - name: Configure promtail
      ansible.builtin.import_role:
        name: tosit.tdp_observability.loki.promtail
        tasks_from: config
    - ansible.builtin.meta: clear_facts # noqa name[missing]
