# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Loki server config
  hosts: loki
  tasks:
    - tosit.tdp.resolve:
        node_name: loki_server
    - ansible.builtin.import_role:
        name: tosit.tdp_observability.loki.server
        tasks_from: config
    - ansible.builtin.meta: clear_facts
