# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Loki Promtail stop
  hosts: promtail
  tasks:
    - tosit.tdp.resolve:
        node_name: loki_promtail
    - import_role:
        name: tosit.tdp_observability.loki.promtail
        tasks_from: stop
    - meta: clear_facts
