# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Prometheus Server Start
  hosts: prometheus
  tasks:
    - tosit.tdp.resolve:
        node_name: prometheus_server
    - ansible.builtin.import_role:
        name: tosit.tdp_observability.prometheus.server
        tasks_from: start
    - ansible.builtin.meta: clear_facts
