# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Prometheus Server Install
  hosts: prometheus
  tasks:
    - tosit.tdp.resolve:                # noqa name[missing]
        node_name: prometheus_server
    - name: Install prometheus server
      ansible.builtin.import_role:
        name: tosit.tdp_observability.prometheus.server
        tasks_from: install
    - ansible.builtin.meta: clear_facts # noqa name[missing]
