# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Prometheus Server Install
  hosts: prometheus
  tasks:
    - tosit.tdp.resolve:
        node_name: prometheus_server
    - import_role:
        name: tosit.tdp_observability.prometheus.server
        tasks_from: install
    - meta: clear_facts
