# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Configure labels
  ansible.builtin.set_fact:
    all_labels: |
      {{ {
           'instance': inventory_hostname,
           'service' : service.key,
           'component': component.key,
           '__path__': job.log_file,
         } |
         combine(observability_common_labels | default({})) |
         combine(service_labels              | default({})) |
         combine(component.value.labels      | default({})) |
         combine(job.labels                  | default({}))
      }}

- name: Determine job_name
  ansible.builtin.set_fact:
    job_name: "{{ service.key }}_{{ component.key }}"

- name: Add suffix to job_name when specified
  ansible.builtin.set_fact:
    job_name: "{{ job_name }}_{{ job.name_suffix }}"
  when: job.name_suffix is defined and job.name_suffix | length > 0

- name: Fail when job_name duplicates a previous job
  ansible.builtin.fail:
    msg: >
      Whooops. job name {{ job_name }} duplicates another scrape config.
      You should use 'name_suffix' when several jobs are configured on the
      same component
  when: job_name in promtail_job_list | default([])

- name: Add job_name to promtail_job_list
  ansible.builtin.set_fact:
    promtail_job_list: "{{ promtail_job_list | default([]) + [job_name] }}"

- name: Set pipeline stage from models in promtail_pipelines
  ansible.builtin.set_fact:
    pipeline: "{{ promtail_pipelines[job.promtail_pipeline | default('default')] | default([]) }}"
  when: job.promtail_pipeline is not defined or job.promtail_pipeline is string

- name: Set pipeline stage (hard coded)
  ansible.builtin.set_fact:
    pipeline: "{{ job.promtail_pipeline }}"
  when: job.promtail_pipeline is defined and job.promtail_pipeline is not string

- name: Add scrape_config
  ansible.builtin.set_fact:
    promtail_scrape_configs: |
      {{ promtail_scrape_configs | default([]) +
        [{
          'job_name': job_name,
          'pipeline_stages': pipeline,
          'static_configs': [{
            'targets': [ 'localhost' ],
            'labels': all_labels
          }]
        }]
      }}
