# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Configure labels
  ansible.builtin.set_fact:
    all_labels: |
      {{ {
           'instance': inventory_hostname,
           'service' : service.key,
           'component': component.key,
         } |
         combine(observability_common_labels | default({})) |
         combine(job.common_labels           | default({})) |
         combine(job.loki_labels             | default({}))
      }}

- name: Determine job_name
  ansible.builtin.set_fact:
    job_name: "{{ service.key }}_{{ component.key }}"

- name: Add suffix to job_name when specified
  ansible.builtin.set_fact:
    job_name: "{{ job_name }}_{{ job.name_suffix }}"
  when: job.name_suffix is defined and job.name_suffix | length > 0

- name: Fail when job_name duplicates a previous job
  ansible.builtin.fail:
    msg: >
      Whooops. job name {{ job_name }} duplicates another scrape config.
      You should use 'name_suffix' when several jobs are configured on the
      same component
  when: job_name in job_list | default([])

- name: Add job_name to job_list
  ansible.builtin.set_fact:
    job_list: "{{ job_list | default([]) + [job_name] }}"

- name: Add scrape_config
  ansible.builtin.set_fact:
    promtail_scrape_configs: |
      {{ promtail_scrape_configs | default([]) +
        [{
          'job_name': job_name,
          'pipeline_stages': [
            { 'multiline': { 'firstline': promtail_date_regex }},
            { 'regex': { 'expression': promtail_log_analyser_regex }},
            { 'template': { 'source': 'level', 'template': '{{ ToLower .Value }}'}},
            { 'timestamp': {
                'format': 'RFC3339',
                'source': 'datetime'
              }
            },
            { 'labels': promtail_log_analyser_labels },
          ],
          'static_configs': [{
            'targets': [ 'localhost' ],
            'labels': all_labels | combine({
              '__path__': job.log_file
            })
          }]
        }]
      }}
