# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Parse promtail scrape configs
  ansible.builtin.include_tasks: config_promtail_scrapes.yml
  when:
    - job.enabled | default(true)
    - job.log_file is defined and job.log_file  | length > 0
  loop: "{{ component.value.jobs }}"
  loop_control:
    loop_var: job
    index_var: job_num
    label: "{{ service.key }}_{{ component.key }}_{{ job_num }}"
