# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Ensure promtail's group exists  # noqa var-naming[no-role-prefix]
  ansible.builtin.include_role:
    name: tosit.tdp.utils.group
  vars:
    group: "{{ promtail_group }}"

- name: Ensure promtail's user exists   # noqa var-naming[no-role-prefix]
  ansible.builtin.user:
    name: "{{ promtail_user }}"
    group: "{{ promtail_group }}"
    groups: "{{ promtail_secondary_groups }}"

- name: "Upload {{ promtail_dist_file }}"
  ansible.builtin.copy:
    src: "{{ binaries_local_dir }}/{{ promtail_dist_file }}"
    dest: "{{ binaries_upload_dir }}/{{ promtail_dist_file }}"
    owner: root
    group: root
    mode: "644"
  diff: false

- name: "Ensure directory exists : {{ promtail_release }}"
  ansible.builtin.file:
    path: "{{ promtail_root_dir }}/{{ promtail_release }}"
    state: directory
    owner: root
    group: root
    mode: "755"

- name: "Extract {{ promtail_dist_file }}"
  ansible.builtin.unarchive:
    src: "{{ binaries_upload_dir }}/{{ promtail_dist_file }}"
    dest: "{{ promtail_root_dir }}/{{ promtail_release }}"
    group: root
    owner: root
    mode: "755"
    remote_src: true
    creates: "{{ promtail_root_dir }}/{{ promtail_release }}/promtail-linux-amd64"

- name: Create symbolic link to promtail installation
  ansible.builtin.file:
    src: "{{ promtail_root_dir }}/{{ promtail_release }}"
    dest: "{{ promtail_install_dir }}"
    state: link

- name: Ensure promtail data and log directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ promtail_user }}"
    group: "{{ promtail_group }}"
    mode: "750"
  with_items:
    - "{{ promtail_data_dir }}"
    - "{{ promtail_log_dir }}"

- name: "Ensure directory exists: {{ promtail_conf_dir }}"
  ansible.builtin.file:
    path: "{{ promtail_conf_dir }}"
    state: directory
    owner: "{{ promtail_user }}"
    group: "{{ promtail_group }}"
    mode: "755"

- name: Template promtail logrotate file
  ansible.builtin.template:
    src: promtail.logrotate.j2
    dest: "/etc/logrotate.d/promtail"
    group: root
    owner: root
    mode: "644"

- name: Template promtail service file
  ansible.builtin.template:
    src: promtail.service.j2
    dest: /usr/lib/systemd/system/promtail.service
    group: root
    owner: root
    mode: "644"
  notify: systemctl daemon-reload
