# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Restart promtail
  ansible.builtin.service:
    name: promtail
    state: restarted
    enabled: "{{ promtail_start_on_boot }}"
