# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Stop promtail
  ansible.builtin.service:
    name: promtail
    state: stopped
    enabled: "{{ promtail_start_on_boot }}"
