{
 "title": "Jmx metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   { "name": "service", "query": { "query": "label_values(service)" } },
   {
    "name": "job",
    "query": {
     "query": "label_values(up{service=\"${service}\"},job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=\"${job}\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><p style=\"text-align: center;\">${job} jmx metrics</p></h1>"
   }
  },
  {
   "title": "OpenFileDescriptorCount",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{job=\"${job}\", instance=~\"${instance}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "maximum jvm classes loaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_classes_loaded{job=\"${job}\", instance=~\"${instance}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jvm_threads_deadlocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_threads_deadlocked{job=\"${job}\", instance=~\"${instance}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory pool bytes used (HEAP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=\"${job}\", instance=~\"${instance}\", pool=~\"PS.*\"}",
     "legendFormat": "{{instance}} pool:{{pool}}"
    }
   ]
  },
  {
   "title": "Memory pool bytes used (non HEAP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=\"${job}\", instance=~\"${instance}\", pool!~\"PS.*\"}",
     "legendFormat": "{{instance}} pool:{{pool}}"
    }
   ]
  },
  {
   "title": "current jvm threads (max)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_threads_current{job=\"${job}\", instance=~\"${instance}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "threads state (waiting)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{job=\"${job}\", instance=~\"${instance}\", state=~\"^(BLOCKED|TIMED_WAITING|WAITING).*\"}",
     "legendFormat": "{{instance}} state:{{state}}"
    }
   ]
  },
  {
   "title": "threads state (not waiting)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{job=\"${job}\", instance=~\"${instance}\", state!~\"^(BLOCKED|TIMED_WAITING|WAITING).*\"}",
     "legendFormat": "{{instance}} state:{{state}}"
    }
   ]
  },
  {
   "title": "gc collection seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"${job}\", instance=~\"${instance}\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}