{
 "title": "Python Process",
 "description": "Metrics related to python",
 "tags": [ "python" ],
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "service",
    "label": "Instance",
    "query": {
     "query": "label_values(python_info,service)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(up{service!=\"\",service=\"${service}\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><p style=\"text-align: center;\">${job} metrics</p></h1>"
   }
  },
  {
   "title": "Python Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "python_info{job=~\"$job\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\"}[$__interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max file descriptors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "timeseries",
   "description": "Number of objects collected during gc.\t",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total{job=~\"$job\"}[$__interval])",
     "legendFormat": "collected - gen {{ generation }}"
    }
   ]
  }
 ]
}