# Copyright 2022 TOSIT.IO
# SPDX-License-Identifier: Apache-2.0

---
- name: Start postgres-exporter
  ansible.builtin.service:
    name: postgres-exporter
    state: started
    enabled: "{{ postgres_exporter_start_on_boot }}"
