name: Ansible Lint
on:
  push
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out TOSIT-IO/tdp-collection
        uses: actions/checkout@v3
        with:
          repository: TOSIT-IO/tdp-collection
          path: ansible_collections/tosit/tdp
      - uses: actions/checkout@v3
      - run: |
          dev/setup.sh
          source venv/bin/activate
          export ANSIBLE_COLLECTIONS_PATH=$PWD
          ansible-lint
