name: Conventional Commits
on: 
  push
jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          echo ${{ github.event_name == 'push' && github.event.before'..'github.event.after || github.event.pull_request.base.sha'..'github.event.pull_request.head.sha  }}
          echo ${{ github.event.before }}
          echo ${{ github.event.base_ref }}
      - uses: webiny/action-conventional-commits@v1.0.3
