name: Conventional Commits
on: 
  push
jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.before }}
          echo ${{ github.event.base_ref }}
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.0.3
