name: Conventional Commits
on: 
  push:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  FORCE_COLOR: true

jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup testing environment
        run: dev/setup.sh
      - name: Check license headers
        run: source venv/bin/activate && dev/license_check.py
