name: Conventional Commits
on: 
  pull_request:
    types: [opened, reopened, synchronize]

env:
  FORCE_COLOR: true
  COMMITRANGE: >-
    ${{ 
      github.event_name == 'pull_request' 
          && format('{0}..{1}', github.event.pull_request.base.sha,github.event.pull_request.head.sha) 
          || ( github.event_name == 'push' 
             && ( startsWith(github.event.before, '0000000') && 'HEAD~..' 
             || format('{0}..{1}', github.event.before, github.event.after) 
             )
          ) 
    }}

jobs:
  check-conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup testing environment 
        run: dev/setup.sh
      - name: Check commit messages
        run: source venv/bin/activate && dev/commit_messages.py ${{ env.COMMITRANGE }}
